package com.emate.shop.mapper;

import com.emate.shop.business.model.CountermanScoreRecord;
import com.emate.shop.business.model.CountermanScoreRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountermanScoreRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    int countByExample(CountermanScoreRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    int deleteByExample(CountermanScoreRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    int insert(CountermanScoreRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    int insertSelective(CountermanScoreRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    List<CountermanScoreRecord> selectByExample(CountermanScoreRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    CountermanScoreRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") CountermanScoreRecord record, @Param("example") CountermanScoreRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    int updateByExample(@Param("record") CountermanScoreRecord record, @Param("example") CountermanScoreRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    int updateByPrimaryKeySelective(CountermanScoreRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_score_record
     *
     * @mbggenerated Wed Aug 02 16:26:52 CST 2017
     */
    int updateByPrimaryKey(CountermanScoreRecord record);
}