package com.emate.shop.mapper;

import com.emate.shop.business.model.ImportUserInfo;
import com.emate.shop.business.model.ImportUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImportUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    int countByExample(ImportUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    int deleteByExample(ImportUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    int insert(ImportUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    int insertSelective(ImportUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    List<ImportUserInfo> selectByExample(ImportUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    ImportUserInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") ImportUserInfo record, @Param("example") ImportUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    int updateByExample(@Param("record") ImportUserInfo record, @Param("example") ImportUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    int updateByPrimaryKeySelective(ImportUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_user_info
     *
     * @mbggenerated Thu Aug 23 17:10:49 CST 2018
     */
    int updateByPrimaryKey(ImportUserInfo record);
}