package com.emate.shop.business.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GyOilLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    protected Integer limitEnd;

    public static final String ID_ASC = "id asc";

    public static final String ID_DESC = "id desc";

    public static final String USER_ID_ASC = "user_id asc";

    public static final String USER_ID_DESC = "user_id desc";

    public static final String GAMEID_ASC = "gameid asc";

    public static final String GAMEID_DESC = "gameid desc";

    public static final String SUPPLIER_ASC = "supplier asc";

    public static final String SUPPLIER_DESC = "supplier desc";

    public static final String PROVIDER_ASC = "provider asc";

    public static final String PROVIDER_DESC = "provider desc";

    public static final String PARENT_ORDER_NO_ASC = "parent_order_no asc";

    public static final String PARENT_ORDER_NO_DESC = "parent_order_no desc";

    public static final String ORDERID_ASC = "orderid asc";

    public static final String ORDERID_DESC = "orderid desc";

    public static final String JXORDERID_ASC = "jxorderid asc";

    public static final String JXORDERID_DESC = "jxorderid desc";

    public static final String GASCARDID_ASC = "gascardid asc";

    public static final String GASCARDID_DESC = "gascardid desc";

    public static final String CHARGETYPE_ASC = "chargetype asc";

    public static final String CHARGETYPE_DESC = "chargetype desc";

    public static final String PARVALUE_ASC = "parvalue asc";

    public static final String PARVALUE_DESC = "parvalue desc";

    public static final String FILLNUM_ASC = "fillnum asc";

    public static final String FILLNUM_DESC = "fillnum desc";

    public static final String ORDERSTATUS_ASC = "orderstatus asc";

    public static final String ORDERSTATUS_DESC = "orderstatus desc";

    public static final String ERRDESC_ASC = "errdesc asc";

    public static final String ERRDESC_DESC = "errdesc desc";

    public static final String RESULTCODE_ASC = "resultcode asc";

    public static final String RESULTCODE_DESC = "resultcode desc";

    public static final String GASCARDTEL_ASC = "gascardtel asc";

    public static final String GASCARDTEL_DESC = "gascardtel desc";

    public static final String GASCARDNAME_ASC = "gascardname asc";

    public static final String GASCARDNAME_DESC = "gascardname desc";

    public static final String USERIP_ASC = "userip asc";

    public static final String USERIP_DESC = "userip desc";

    public static final String FILLMONEY_ASC = "fillmoney asc";

    public static final String FILLMONEY_DESC = "fillmoney desc";

    public static final String FINISHMONEY_ASC = "finishmoney asc";

    public static final String FINISHMONEY_DESC = "finishmoney desc";

    public static final String SHOP_MONEY_ASC = "shop_money asc";

    public static final String SHOP_MONEY_DESC = "shop_money desc";

    public static final String SURPLUS_MONEY_ASC = "surplus_money asc";

    public static final String SURPLUS_MONEY_DESC = "surplus_money desc";

    public static final String FINISHTIME_ASC = "finishtime asc";

    public static final String FINISHTIME_DESC = "finishtime desc";

    public static final String REQUEST_NUM_ASC = "request_num asc";

    public static final String REQUEST_NUM_DESC = "request_num desc";

    public static final String CREATE_TIME_ASC = "create_time asc";

    public static final String CREATE_TIME_DESC = "create_time desc";

    public static final String UPDATE_TIME_ASC = "update_time asc";

    public static final String UPDATE_TIME_DESC = "update_time desc";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public GyOilLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andGameidIsNull() {
            addCriterion("gameid is null");
            return (Criteria) this;
        }

        public Criteria andGameidIsNotNull() {
            addCriterion("gameid is not null");
            return (Criteria) this;
        }

        public Criteria andGameidEqualTo(String value) {
            addCriterion("gameid =", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotEqualTo(String value) {
            addCriterion("gameid <>", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidGreaterThan(String value) {
            addCriterion("gameid >", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidGreaterThanOrEqualTo(String value) {
            addCriterion("gameid >=", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidLessThan(String value) {
            addCriterion("gameid <", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidLessThanOrEqualTo(String value) {
            addCriterion("gameid <=", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidLike(String value) {
            addCriterion("gameid like", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotLike(String value) {
            addCriterion("gameid not like", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidIn(List<String> values) {
            addCriterion("gameid in", values, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotIn(List<String> values) {
            addCriterion("gameid not in", values, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidBetween(String value1, String value2) {
            addCriterion("gameid between", value1, value2, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotBetween(String value1, String value2) {
            addCriterion("gameid not between", value1, value2, "gameid");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNull() {
            addCriterion("supplier is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNotNull() {
            addCriterion("supplier is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierEqualTo(Integer value) {
            addCriterion("supplier =", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotEqualTo(Integer value) {
            addCriterion("supplier <>", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThan(Integer value) {
            addCriterion("supplier >", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThanOrEqualTo(Integer value) {
            addCriterion("supplier >=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThan(Integer value) {
            addCriterion("supplier <", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThanOrEqualTo(Integer value) {
            addCriterion("supplier <=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierIn(List<Integer> values) {
            addCriterion("supplier in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotIn(List<Integer> values) {
            addCriterion("supplier not in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierBetween(Integer value1, Integer value2) {
            addCriterion("supplier between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotBetween(Integer value1, Integer value2) {
            addCriterion("supplier not between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andProviderIsNull() {
            addCriterion("provider is null");
            return (Criteria) this;
        }

        public Criteria andProviderIsNotNull() {
            addCriterion("provider is not null");
            return (Criteria) this;
        }

        public Criteria andProviderEqualTo(Integer value) {
            addCriterion("provider =", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderNotEqualTo(Integer value) {
            addCriterion("provider <>", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderGreaterThan(Integer value) {
            addCriterion("provider >", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderGreaterThanOrEqualTo(Integer value) {
            addCriterion("provider >=", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderLessThan(Integer value) {
            addCriterion("provider <", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderLessThanOrEqualTo(Integer value) {
            addCriterion("provider <=", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderIn(List<Integer> values) {
            addCriterion("provider in", values, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderNotIn(List<Integer> values) {
            addCriterion("provider not in", values, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderBetween(Integer value1, Integer value2) {
            addCriterion("provider between", value1, value2, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderNotBetween(Integer value1, Integer value2) {
            addCriterion("provider not between", value1, value2, "provider");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoIsNull() {
            addCriterion("parent_order_no is null");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoIsNotNull() {
            addCriterion("parent_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoEqualTo(String value) {
            addCriterion("parent_order_no =", value, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoNotEqualTo(String value) {
            addCriterion("parent_order_no <>", value, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoGreaterThan(String value) {
            addCriterion("parent_order_no >", value, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("parent_order_no >=", value, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoLessThan(String value) {
            addCriterion("parent_order_no <", value, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoLessThanOrEqualTo(String value) {
            addCriterion("parent_order_no <=", value, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoLike(String value) {
            addCriterion("parent_order_no like", value, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoNotLike(String value) {
            addCriterion("parent_order_no not like", value, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoIn(List<String> values) {
            addCriterion("parent_order_no in", values, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoNotIn(List<String> values) {
            addCriterion("parent_order_no not in", values, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoBetween(String value1, String value2) {
            addCriterion("parent_order_no between", value1, value2, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentOrderNoNotBetween(String value1, String value2) {
            addCriterion("parent_order_no not between", value1, value2, "parentOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderid is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("orderid =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("orderid <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("orderid >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("orderid >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("orderid <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("orderid <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("orderid like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("orderid not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("orderid in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("orderid not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("orderid between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("orderid not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidIsNull() {
            addCriterion("jxorderid is null");
            return (Criteria) this;
        }

        public Criteria andJxorderidIsNotNull() {
            addCriterion("jxorderid is not null");
            return (Criteria) this;
        }

        public Criteria andJxorderidEqualTo(String value) {
            addCriterion("jxorderid =", value, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidNotEqualTo(String value) {
            addCriterion("jxorderid <>", value, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidGreaterThan(String value) {
            addCriterion("jxorderid >", value, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidGreaterThanOrEqualTo(String value) {
            addCriterion("jxorderid >=", value, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidLessThan(String value) {
            addCriterion("jxorderid <", value, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidLessThanOrEqualTo(String value) {
            addCriterion("jxorderid <=", value, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidLike(String value) {
            addCriterion("jxorderid like", value, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidNotLike(String value) {
            addCriterion("jxorderid not like", value, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidIn(List<String> values) {
            addCriterion("jxorderid in", values, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidNotIn(List<String> values) {
            addCriterion("jxorderid not in", values, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidBetween(String value1, String value2) {
            addCriterion("jxorderid between", value1, value2, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andJxorderidNotBetween(String value1, String value2) {
            addCriterion("jxorderid not between", value1, value2, "jxorderid");
            return (Criteria) this;
        }

        public Criteria andGascardidIsNull() {
            addCriterion("gascardid is null");
            return (Criteria) this;
        }

        public Criteria andGascardidIsNotNull() {
            addCriterion("gascardid is not null");
            return (Criteria) this;
        }

        public Criteria andGascardidEqualTo(String value) {
            addCriterion("gascardid =", value, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidNotEqualTo(String value) {
            addCriterion("gascardid <>", value, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidGreaterThan(String value) {
            addCriterion("gascardid >", value, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidGreaterThanOrEqualTo(String value) {
            addCriterion("gascardid >=", value, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidLessThan(String value) {
            addCriterion("gascardid <", value, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidLessThanOrEqualTo(String value) {
            addCriterion("gascardid <=", value, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidLike(String value) {
            addCriterion("gascardid like", value, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidNotLike(String value) {
            addCriterion("gascardid not like", value, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidIn(List<String> values) {
            addCriterion("gascardid in", values, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidNotIn(List<String> values) {
            addCriterion("gascardid not in", values, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidBetween(String value1, String value2) {
            addCriterion("gascardid between", value1, value2, "gascardid");
            return (Criteria) this;
        }

        public Criteria andGascardidNotBetween(String value1, String value2) {
            addCriterion("gascardid not between", value1, value2, "gascardid");
            return (Criteria) this;
        }

        public Criteria andChargetypeIsNull() {
            addCriterion("chargetype is null");
            return (Criteria) this;
        }

        public Criteria andChargetypeIsNotNull() {
            addCriterion("chargetype is not null");
            return (Criteria) this;
        }

        public Criteria andChargetypeEqualTo(Byte value) {
            addCriterion("chargetype =", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeNotEqualTo(Byte value) {
            addCriterion("chargetype <>", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeGreaterThan(Byte value) {
            addCriterion("chargetype >", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("chargetype >=", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeLessThan(Byte value) {
            addCriterion("chargetype <", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeLessThanOrEqualTo(Byte value) {
            addCriterion("chargetype <=", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeIn(List<Byte> values) {
            addCriterion("chargetype in", values, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeNotIn(List<Byte> values) {
            addCriterion("chargetype not in", values, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeBetween(Byte value1, Byte value2) {
            addCriterion("chargetype between", value1, value2, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeNotBetween(Byte value1, Byte value2) {
            addCriterion("chargetype not between", value1, value2, "chargetype");
            return (Criteria) this;
        }

        public Criteria andParvalueIsNull() {
            addCriterion("parvalue is null");
            return (Criteria) this;
        }

        public Criteria andParvalueIsNotNull() {
            addCriterion("parvalue is not null");
            return (Criteria) this;
        }

        public Criteria andParvalueEqualTo(BigDecimal value) {
            addCriterion("parvalue =", value, "parvalue");
            return (Criteria) this;
        }

        public Criteria andParvalueNotEqualTo(BigDecimal value) {
            addCriterion("parvalue <>", value, "parvalue");
            return (Criteria) this;
        }

        public Criteria andParvalueGreaterThan(BigDecimal value) {
            addCriterion("parvalue >", value, "parvalue");
            return (Criteria) this;
        }

        public Criteria andParvalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("parvalue >=", value, "parvalue");
            return (Criteria) this;
        }

        public Criteria andParvalueLessThan(BigDecimal value) {
            addCriterion("parvalue <", value, "parvalue");
            return (Criteria) this;
        }

        public Criteria andParvalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("parvalue <=", value, "parvalue");
            return (Criteria) this;
        }

        public Criteria andParvalueIn(List<BigDecimal> values) {
            addCriterion("parvalue in", values, "parvalue");
            return (Criteria) this;
        }

        public Criteria andParvalueNotIn(List<BigDecimal> values) {
            addCriterion("parvalue not in", values, "parvalue");
            return (Criteria) this;
        }

        public Criteria andParvalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("parvalue between", value1, value2, "parvalue");
            return (Criteria) this;
        }

        public Criteria andParvalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("parvalue not between", value1, value2, "parvalue");
            return (Criteria) this;
        }

        public Criteria andFillnumIsNull() {
            addCriterion("fillnum is null");
            return (Criteria) this;
        }

        public Criteria andFillnumIsNotNull() {
            addCriterion("fillnum is not null");
            return (Criteria) this;
        }

        public Criteria andFillnumEqualTo(Integer value) {
            addCriterion("fillnum =", value, "fillnum");
            return (Criteria) this;
        }

        public Criteria andFillnumNotEqualTo(Integer value) {
            addCriterion("fillnum <>", value, "fillnum");
            return (Criteria) this;
        }

        public Criteria andFillnumGreaterThan(Integer value) {
            addCriterion("fillnum >", value, "fillnum");
            return (Criteria) this;
        }

        public Criteria andFillnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("fillnum >=", value, "fillnum");
            return (Criteria) this;
        }

        public Criteria andFillnumLessThan(Integer value) {
            addCriterion("fillnum <", value, "fillnum");
            return (Criteria) this;
        }

        public Criteria andFillnumLessThanOrEqualTo(Integer value) {
            addCriterion("fillnum <=", value, "fillnum");
            return (Criteria) this;
        }

        public Criteria andFillnumIn(List<Integer> values) {
            addCriterion("fillnum in", values, "fillnum");
            return (Criteria) this;
        }

        public Criteria andFillnumNotIn(List<Integer> values) {
            addCriterion("fillnum not in", values, "fillnum");
            return (Criteria) this;
        }

        public Criteria andFillnumBetween(Integer value1, Integer value2) {
            addCriterion("fillnum between", value1, value2, "fillnum");
            return (Criteria) this;
        }

        public Criteria andFillnumNotBetween(Integer value1, Integer value2) {
            addCriterion("fillnum not between", value1, value2, "fillnum");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIsNull() {
            addCriterion("orderstatus is null");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIsNotNull() {
            addCriterion("orderstatus is not null");
            return (Criteria) this;
        }

        public Criteria andOrderstatusEqualTo(Byte value) {
            addCriterion("orderstatus =", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotEqualTo(Byte value) {
            addCriterion("orderstatus <>", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusGreaterThan(Byte value) {
            addCriterion("orderstatus >", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("orderstatus >=", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLessThan(Byte value) {
            addCriterion("orderstatus <", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLessThanOrEqualTo(Byte value) {
            addCriterion("orderstatus <=", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIn(List<Byte> values) {
            addCriterion("orderstatus in", values, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotIn(List<Byte> values) {
            addCriterion("orderstatus not in", values, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusBetween(Byte value1, Byte value2) {
            addCriterion("orderstatus between", value1, value2, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotBetween(Byte value1, Byte value2) {
            addCriterion("orderstatus not between", value1, value2, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andErrdescIsNull() {
            addCriterion("errdesc is null");
            return (Criteria) this;
        }

        public Criteria andErrdescIsNotNull() {
            addCriterion("errdesc is not null");
            return (Criteria) this;
        }

        public Criteria andErrdescEqualTo(String value) {
            addCriterion("errdesc =", value, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescNotEqualTo(String value) {
            addCriterion("errdesc <>", value, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescGreaterThan(String value) {
            addCriterion("errdesc >", value, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescGreaterThanOrEqualTo(String value) {
            addCriterion("errdesc >=", value, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescLessThan(String value) {
            addCriterion("errdesc <", value, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescLessThanOrEqualTo(String value) {
            addCriterion("errdesc <=", value, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescLike(String value) {
            addCriterion("errdesc like", value, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescNotLike(String value) {
            addCriterion("errdesc not like", value, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescIn(List<String> values) {
            addCriterion("errdesc in", values, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescNotIn(List<String> values) {
            addCriterion("errdesc not in", values, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescBetween(String value1, String value2) {
            addCriterion("errdesc between", value1, value2, "errdesc");
            return (Criteria) this;
        }

        public Criteria andErrdescNotBetween(String value1, String value2) {
            addCriterion("errdesc not between", value1, value2, "errdesc");
            return (Criteria) this;
        }

        public Criteria andResultcodeIsNull() {
            addCriterion("resultcode is null");
            return (Criteria) this;
        }

        public Criteria andResultcodeIsNotNull() {
            addCriterion("resultcode is not null");
            return (Criteria) this;
        }

        public Criteria andResultcodeEqualTo(String value) {
            addCriterion("resultcode =", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeNotEqualTo(String value) {
            addCriterion("resultcode <>", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeGreaterThan(String value) {
            addCriterion("resultcode >", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeGreaterThanOrEqualTo(String value) {
            addCriterion("resultcode >=", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeLessThan(String value) {
            addCriterion("resultcode <", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeLessThanOrEqualTo(String value) {
            addCriterion("resultcode <=", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeLike(String value) {
            addCriterion("resultcode like", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeNotLike(String value) {
            addCriterion("resultcode not like", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeIn(List<String> values) {
            addCriterion("resultcode in", values, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeNotIn(List<String> values) {
            addCriterion("resultcode not in", values, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeBetween(String value1, String value2) {
            addCriterion("resultcode between", value1, value2, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeNotBetween(String value1, String value2) {
            addCriterion("resultcode not between", value1, value2, "resultcode");
            return (Criteria) this;
        }

        public Criteria andGascardtelIsNull() {
            addCriterion("gascardtel is null");
            return (Criteria) this;
        }

        public Criteria andGascardtelIsNotNull() {
            addCriterion("gascardtel is not null");
            return (Criteria) this;
        }

        public Criteria andGascardtelEqualTo(String value) {
            addCriterion("gascardtel =", value, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelNotEqualTo(String value) {
            addCriterion("gascardtel <>", value, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelGreaterThan(String value) {
            addCriterion("gascardtel >", value, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelGreaterThanOrEqualTo(String value) {
            addCriterion("gascardtel >=", value, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelLessThan(String value) {
            addCriterion("gascardtel <", value, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelLessThanOrEqualTo(String value) {
            addCriterion("gascardtel <=", value, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelLike(String value) {
            addCriterion("gascardtel like", value, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelNotLike(String value) {
            addCriterion("gascardtel not like", value, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelIn(List<String> values) {
            addCriterion("gascardtel in", values, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelNotIn(List<String> values) {
            addCriterion("gascardtel not in", values, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelBetween(String value1, String value2) {
            addCriterion("gascardtel between", value1, value2, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardtelNotBetween(String value1, String value2) {
            addCriterion("gascardtel not between", value1, value2, "gascardtel");
            return (Criteria) this;
        }

        public Criteria andGascardnameIsNull() {
            addCriterion("gascardname is null");
            return (Criteria) this;
        }

        public Criteria andGascardnameIsNotNull() {
            addCriterion("gascardname is not null");
            return (Criteria) this;
        }

        public Criteria andGascardnameEqualTo(String value) {
            addCriterion("gascardname =", value, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameNotEqualTo(String value) {
            addCriterion("gascardname <>", value, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameGreaterThan(String value) {
            addCriterion("gascardname >", value, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameGreaterThanOrEqualTo(String value) {
            addCriterion("gascardname >=", value, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameLessThan(String value) {
            addCriterion("gascardname <", value, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameLessThanOrEqualTo(String value) {
            addCriterion("gascardname <=", value, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameLike(String value) {
            addCriterion("gascardname like", value, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameNotLike(String value) {
            addCriterion("gascardname not like", value, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameIn(List<String> values) {
            addCriterion("gascardname in", values, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameNotIn(List<String> values) {
            addCriterion("gascardname not in", values, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameBetween(String value1, String value2) {
            addCriterion("gascardname between", value1, value2, "gascardname");
            return (Criteria) this;
        }

        public Criteria andGascardnameNotBetween(String value1, String value2) {
            addCriterion("gascardname not between", value1, value2, "gascardname");
            return (Criteria) this;
        }

        public Criteria andUseripIsNull() {
            addCriterion("userip is null");
            return (Criteria) this;
        }

        public Criteria andUseripIsNotNull() {
            addCriterion("userip is not null");
            return (Criteria) this;
        }

        public Criteria andUseripEqualTo(String value) {
            addCriterion("userip =", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripNotEqualTo(String value) {
            addCriterion("userip <>", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripGreaterThan(String value) {
            addCriterion("userip >", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripGreaterThanOrEqualTo(String value) {
            addCriterion("userip >=", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripLessThan(String value) {
            addCriterion("userip <", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripLessThanOrEqualTo(String value) {
            addCriterion("userip <=", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripLike(String value) {
            addCriterion("userip like", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripNotLike(String value) {
            addCriterion("userip not like", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripIn(List<String> values) {
            addCriterion("userip in", values, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripNotIn(List<String> values) {
            addCriterion("userip not in", values, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripBetween(String value1, String value2) {
            addCriterion("userip between", value1, value2, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripNotBetween(String value1, String value2) {
            addCriterion("userip not between", value1, value2, "userip");
            return (Criteria) this;
        }

        public Criteria andFillmoneyIsNull() {
            addCriterion("fillmoney is null");
            return (Criteria) this;
        }

        public Criteria andFillmoneyIsNotNull() {
            addCriterion("fillmoney is not null");
            return (Criteria) this;
        }

        public Criteria andFillmoneyEqualTo(BigDecimal value) {
            addCriterion("fillmoney =", value, "fillmoney");
            return (Criteria) this;
        }

        public Criteria andFillmoneyNotEqualTo(BigDecimal value) {
            addCriterion("fillmoney <>", value, "fillmoney");
            return (Criteria) this;
        }

        public Criteria andFillmoneyGreaterThan(BigDecimal value) {
            addCriterion("fillmoney >", value, "fillmoney");
            return (Criteria) this;
        }

        public Criteria andFillmoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fillmoney >=", value, "fillmoney");
            return (Criteria) this;
        }

        public Criteria andFillmoneyLessThan(BigDecimal value) {
            addCriterion("fillmoney <", value, "fillmoney");
            return (Criteria) this;
        }

        public Criteria andFillmoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fillmoney <=", value, "fillmoney");
            return (Criteria) this;
        }

        public Criteria andFillmoneyIn(List<BigDecimal> values) {
            addCriterion("fillmoney in", values, "fillmoney");
            return (Criteria) this;
        }

        public Criteria andFillmoneyNotIn(List<BigDecimal> values) {
            addCriterion("fillmoney not in", values, "fillmoney");
            return (Criteria) this;
        }

        public Criteria andFillmoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fillmoney between", value1, value2, "fillmoney");
            return (Criteria) this;
        }

        public Criteria andFillmoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fillmoney not between", value1, value2, "fillmoney");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyIsNull() {
            addCriterion("finishmoney is null");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyIsNotNull() {
            addCriterion("finishmoney is not null");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyEqualTo(BigDecimal value) {
            addCriterion("finishmoney =", value, "finishmoney");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyNotEqualTo(BigDecimal value) {
            addCriterion("finishmoney <>", value, "finishmoney");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyGreaterThan(BigDecimal value) {
            addCriterion("finishmoney >", value, "finishmoney");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("finishmoney >=", value, "finishmoney");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyLessThan(BigDecimal value) {
            addCriterion("finishmoney <", value, "finishmoney");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("finishmoney <=", value, "finishmoney");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyIn(List<BigDecimal> values) {
            addCriterion("finishmoney in", values, "finishmoney");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyNotIn(List<BigDecimal> values) {
            addCriterion("finishmoney not in", values, "finishmoney");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("finishmoney between", value1, value2, "finishmoney");
            return (Criteria) this;
        }

        public Criteria andFinishmoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("finishmoney not between", value1, value2, "finishmoney");
            return (Criteria) this;
        }

        public Criteria andShopMoneyIsNull() {
            addCriterion("shop_money is null");
            return (Criteria) this;
        }

        public Criteria andShopMoneyIsNotNull() {
            addCriterion("shop_money is not null");
            return (Criteria) this;
        }

        public Criteria andShopMoneyEqualTo(BigDecimal value) {
            addCriterion("shop_money =", value, "shopMoney");
            return (Criteria) this;
        }

        public Criteria andShopMoneyNotEqualTo(BigDecimal value) {
            addCriterion("shop_money <>", value, "shopMoney");
            return (Criteria) this;
        }

        public Criteria andShopMoneyGreaterThan(BigDecimal value) {
            addCriterion("shop_money >", value, "shopMoney");
            return (Criteria) this;
        }

        public Criteria andShopMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shop_money >=", value, "shopMoney");
            return (Criteria) this;
        }

        public Criteria andShopMoneyLessThan(BigDecimal value) {
            addCriterion("shop_money <", value, "shopMoney");
            return (Criteria) this;
        }

        public Criteria andShopMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shop_money <=", value, "shopMoney");
            return (Criteria) this;
        }

        public Criteria andShopMoneyIn(List<BigDecimal> values) {
            addCriterion("shop_money in", values, "shopMoney");
            return (Criteria) this;
        }

        public Criteria andShopMoneyNotIn(List<BigDecimal> values) {
            addCriterion("shop_money not in", values, "shopMoney");
            return (Criteria) this;
        }

        public Criteria andShopMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shop_money between", value1, value2, "shopMoney");
            return (Criteria) this;
        }

        public Criteria andShopMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shop_money not between", value1, value2, "shopMoney");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyIsNull() {
            addCriterion("surplus_money is null");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyIsNotNull() {
            addCriterion("surplus_money is not null");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyEqualTo(BigDecimal value) {
            addCriterion("surplus_money =", value, "surplusMoney");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyNotEqualTo(BigDecimal value) {
            addCriterion("surplus_money <>", value, "surplusMoney");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyGreaterThan(BigDecimal value) {
            addCriterion("surplus_money >", value, "surplusMoney");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("surplus_money >=", value, "surplusMoney");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyLessThan(BigDecimal value) {
            addCriterion("surplus_money <", value, "surplusMoney");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("surplus_money <=", value, "surplusMoney");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyIn(List<BigDecimal> values) {
            addCriterion("surplus_money in", values, "surplusMoney");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyNotIn(List<BigDecimal> values) {
            addCriterion("surplus_money not in", values, "surplusMoney");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("surplus_money between", value1, value2, "surplusMoney");
            return (Criteria) this;
        }

        public Criteria andSurplusMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("surplus_money not between", value1, value2, "surplusMoney");
            return (Criteria) this;
        }

        public Criteria andFinishtimeIsNull() {
            addCriterion("finishtime is null");
            return (Criteria) this;
        }

        public Criteria andFinishtimeIsNotNull() {
            addCriterion("finishtime is not null");
            return (Criteria) this;
        }

        public Criteria andFinishtimeEqualTo(Date value) {
            addCriterion("finishtime =", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeNotEqualTo(Date value) {
            addCriterion("finishtime <>", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeGreaterThan(Date value) {
            addCriterion("finishtime >", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("finishtime >=", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeLessThan(Date value) {
            addCriterion("finishtime <", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeLessThanOrEqualTo(Date value) {
            addCriterion("finishtime <=", value, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeIn(List<Date> values) {
            addCriterion("finishtime in", values, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeNotIn(List<Date> values) {
            addCriterion("finishtime not in", values, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeBetween(Date value1, Date value2) {
            addCriterion("finishtime between", value1, value2, "finishtime");
            return (Criteria) this;
        }

        public Criteria andFinishtimeNotBetween(Date value1, Date value2) {
            addCriterion("finishtime not between", value1, value2, "finishtime");
            return (Criteria) this;
        }

        public Criteria andRequestNumIsNull() {
            addCriterion("request_num is null");
            return (Criteria) this;
        }

        public Criteria andRequestNumIsNotNull() {
            addCriterion("request_num is not null");
            return (Criteria) this;
        }

        public Criteria andRequestNumEqualTo(Integer value) {
            addCriterion("request_num =", value, "requestNum");
            return (Criteria) this;
        }

        public Criteria andRequestNumNotEqualTo(Integer value) {
            addCriterion("request_num <>", value, "requestNum");
            return (Criteria) this;
        }

        public Criteria andRequestNumGreaterThan(Integer value) {
            addCriterion("request_num >", value, "requestNum");
            return (Criteria) this;
        }

        public Criteria andRequestNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("request_num >=", value, "requestNum");
            return (Criteria) this;
        }

        public Criteria andRequestNumLessThan(Integer value) {
            addCriterion("request_num <", value, "requestNum");
            return (Criteria) this;
        }

        public Criteria andRequestNumLessThanOrEqualTo(Integer value) {
            addCriterion("request_num <=", value, "requestNum");
            return (Criteria) this;
        }

        public Criteria andRequestNumIn(List<Integer> values) {
            addCriterion("request_num in", values, "requestNum");
            return (Criteria) this;
        }

        public Criteria andRequestNumNotIn(List<Integer> values) {
            addCriterion("request_num not in", values, "requestNum");
            return (Criteria) this;
        }

        public Criteria andRequestNumBetween(Integer value1, Integer value2) {
            addCriterion("request_num between", value1, value2, "requestNum");
            return (Criteria) this;
        }

        public Criteria andRequestNumNotBetween(Integer value1, Integer value2) {
            addCriterion("request_num not between", value1, value2, "requestNum");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gy_oil_log
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 23 20:18:42 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gy_oil_log
     *
     * @mbggenerated Mon Apr 23 20:18:42 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}