package com.emate.shop.mapper;

import com.emate.shop.business.model.CountermanCareer;
import com.emate.shop.business.model.CountermanCareerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountermanCareerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    int countByExample(CountermanCareerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    int deleteByExample(CountermanCareerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    int insert(CountermanCareer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    int insertSelective(CountermanCareer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    List<CountermanCareer> selectByExample(CountermanCareerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    CountermanCareer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") CountermanCareer record, @Param("example") CountermanCareerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    int updateByExample(@Param("record") CountermanCareer record, @Param("example") CountermanCareerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    int updateByPrimaryKeySelective(CountermanCareer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_career
     *
     * @mbggenerated Thu Apr 06 11:43:01 CST 2017
     */
    int updateByPrimaryKey(CountermanCareer record);
}