package com.emate.shop.mapper;

import com.emate.shop.business.model.Autobrand;
import com.emate.shop.business.model.AutobrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutobrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoBrand
     *
     * @mbggenerated Fri Aug 05 10:57:37 CST 2016
     */
    int countByExample(AutobrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoBrand
     *
     * @mbggenerated Fri Aug 05 10:57:37 CST 2016
     */
    int deleteByExample(AutobrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoBrand
     *
     * @mbggenerated Fri Aug 05 10:57:37 CST 2016
     */
    int insert(Autobrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoBrand
     *
     * @mbggenerated Fri Aug 05 10:57:37 CST 2016
     */
    int insertSelective(Autobrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoBrand
     *
     * @mbggenerated Fri Aug 05 10:57:37 CST 2016
     */
    List<Autobrand> selectByExample(AutobrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoBrand
     *
     * @mbggenerated Fri Aug 05 10:57:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") Autobrand record, @Param("example") AutobrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoBrand
     *
     * @mbggenerated Fri Aug 05 10:57:37 CST 2016
     */
    int updateByExample(@Param("record") Autobrand record, @Param("example") AutobrandExample example);
}