package com.emate.shop.mapper;

import com.emate.shop.business.model.CountermanLifeCareer;
import com.emate.shop.business.model.CountermanLifeCareerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountermanLifeCareerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    int countByExample(CountermanLifeCareerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    int deleteByExample(CountermanLifeCareerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    int insert(CountermanLifeCareer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    int insertSelective(CountermanLifeCareer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    List<CountermanLifeCareer> selectByExample(CountermanLifeCareerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    CountermanLifeCareer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") CountermanLifeCareer record, @Param("example") CountermanLifeCareerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    int updateByExample(@Param("record") CountermanLifeCareer record, @Param("example") CountermanLifeCareerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    int updateByPrimaryKeySelective(CountermanLifeCareer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_life_career
     *
     * @mbggenerated Fri Apr 07 09:24:42 CST 2017
     */
    int updateByPrimaryKey(CountermanLifeCareer record);
}