package com.emate.shop.mapper;

import com.emate.shop.business.model.CountermanInfo;
import com.emate.shop.business.model.CountermanInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountermanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    int countByExample(CountermanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    int deleteByExample(CountermanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    int insert(CountermanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    int insertSelective(CountermanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    List<CountermanInfo> selectByExample(CountermanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    CountermanInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") CountermanInfo record, @Param("example") CountermanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    int updateByExample(@Param("record") CountermanInfo record, @Param("example") CountermanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    int updateByPrimaryKeySelective(CountermanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counterman_info
     *
     * @mbggenerated Tue Mar 21 14:02:25 CST 2017
     */
    int updateByPrimaryKey(CountermanInfo record);
}