package com.emate.shop.mapper;

import com.emate.shop.business.model.JicaiOrder;
import com.emate.shop.business.model.JicaiOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JicaiOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    int countByExample(JicaiOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    int deleteByExample(JicaiOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    int insert(JicaiOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    int insertSelective(JicaiOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    List<JicaiOrder> selectByExample(JicaiOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    JicaiOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") JicaiOrder record, @Param("example") JicaiOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    int updateByExample(@Param("record") JicaiOrder record, @Param("example") JicaiOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    int updateByPrimaryKeySelective(JicaiOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jicai_order
     *
     * @mbggenerated Thu Dec 22 11:55:12 CST 2016
     */
    int updateByPrimaryKey(JicaiOrder record);
}