package com.emate.shop.mapper;

import com.emate.shop.business.model.Regions;
import com.emate.shop.business.model.RegionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegionsMapper {
	
	/**
	 * 根据省id查询省名称
	 * @param id
	 * @return
	 */
//	String selectProvinceById(Integer id);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    int countByExample(RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    int deleteByExample(RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    int insert(Regions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    int insertSelective(Regions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    List<Regions> selectByExample(RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    Regions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") Regions record, @Param("example") RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    int updateByExample(@Param("record") Regions record, @Param("example") RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    int updateByPrimaryKeySelective(Regions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbggenerated Wed Dec 21 16:13:30 CST 2016
     */
    int updateByPrimaryKey(Regions record);
}