package com.emate.shop.mapper;

import com.emate.shop.business.model.SystemRoleActionRelation;
import com.emate.shop.business.model.SystemRoleActionRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemRoleActionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int countByExample(SystemRoleActionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int deleteByExample(SystemRoleActionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int insert(SystemRoleActionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int insertSelective(SystemRoleActionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    List<SystemRoleActionRelation> selectByExample(SystemRoleActionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    SystemRoleActionRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") SystemRoleActionRelation record, @Param("example") SystemRoleActionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int updateByExample(@Param("record") SystemRoleActionRelation record, @Param("example") SystemRoleActionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int updateByPrimaryKeySelective(SystemRoleActionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_action_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int updateByPrimaryKey(SystemRoleActionRelation record);
}