package com.emate.shop.mapper;

import com.emate.shop.business.model.SystemRolePageRelation;
import com.emate.shop.business.model.SystemRolePageRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemRolePageRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int countByExample(SystemRolePageRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int deleteByExample(SystemRolePageRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int insert(SystemRolePageRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int insertSelective(SystemRolePageRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    List<SystemRolePageRelation> selectByExample(SystemRolePageRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    SystemRolePageRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") SystemRolePageRelation record, @Param("example") SystemRolePageRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int updateByExample(@Param("record") SystemRolePageRelation record, @Param("example") SystemRolePageRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int updateByPrimaryKeySelective(SystemRolePageRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role_page_relation
     *
     * @mbggenerated Mon Sep 12 13:47:19 CST 2016
     */
    int updateByPrimaryKey(SystemRolePageRelation record);
}