package com.emate.shop.mapper;

import com.emate.shop.business.model.SystemUserRoleRelation;
import com.emate.shop.business.model.SystemUserRoleRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemUserRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    int countByExample(SystemUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    int deleteByExample(SystemUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    int insert(SystemUserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    int insertSelective(SystemUserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    List<SystemUserRoleRelation> selectByExample(SystemUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    SystemUserRoleRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") SystemUserRoleRelation record, @Param("example") SystemUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    int updateByExample(@Param("record") SystemUserRoleRelation record, @Param("example") SystemUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    int updateByPrimaryKeySelective(SystemUserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user_role_relation
     *
     * @mbggenerated Mon Sep 12 14:38:50 CST 2016
     */
    int updateByPrimaryKey(SystemUserRoleRelation record);
}