package com.emate.shop.business.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SurveyCenterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    protected Integer limitEnd;

    public static final String ID_ASC = "id asc";

    public static final String ID_DESC = "id desc";

    public static final String NAME_ASC = "name asc";

    public static final String NAME_DESC = "name desc";

    public static final String ADDRESS_ASC = "address asc";

    public static final String ADDRESS_DESC = "address desc";

    public static final String BELONG_GROUP_ASC = "belong_group asc";

    public static final String BELONG_GROUP_DESC = "belong_group desc";

    public static final String MAIN_CAB_ASC = "main_cab asc";

    public static final String MAIN_CAB_DESC = "main_cab desc";

    public static final String REGION_ASC = "region asc";

    public static final String REGION_DESC = "region desc";

    public static final String COOPERATION_ASC = "cooperation asc";

    public static final String COOPERATION_DESC = "cooperation desc";

    public static final String COOPERATION_TIME_ASC = "cooperation_time asc";

    public static final String COOPERATION_TIME_DESC = "cooperation_time desc";

    public static final String PREMIUM_ASC = "premium asc";

    public static final String PREMIUM_DESC = "premium desc";

    public static final String REPLACE_RATE_ASC = "replace_rate asc";

    public static final String REPLACE_RATE_DESC = "replace_rate desc";

    public static final String LOSS_RATION_ASC = "loss_ration asc";

    public static final String LOSS_RATION_DESC = "loss_ration desc";

    public static final String CENTER_POSITION_ASC = "center_position asc";

    public static final String CENTER_POSITION_DESC = "center_position desc";

    public static final String ZHIGONGSI_ASC = "zhigongsi asc";

    public static final String ZHIGONGSI_DESC = "zhigongsi desc";

    public static final String YEWUYUAN_ASC = "yewuyuan asc";

    public static final String YEWUYUAN_DESC = "yewuyuan desc";

    public static final String CITY_ASC = "city asc";

    public static final String CITY_DESC = "city desc";

    public static final String CREATE_TIME_ASC = "create_time asc";

    public static final String CREATE_TIME_DESC = "create_time desc";

    public static final String UPDATE_TIME_ASC = "update_time asc";

    public static final String UPDATE_TIME_DESC = "update_time desc";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public SurveyCenterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andBelongGroupIsNull() {
            addCriterion("belong_group is null");
            return (Criteria) this;
        }

        public Criteria andBelongGroupIsNotNull() {
            addCriterion("belong_group is not null");
            return (Criteria) this;
        }

        public Criteria andBelongGroupEqualTo(String value) {
            addCriterion("belong_group =", value, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupNotEqualTo(String value) {
            addCriterion("belong_group <>", value, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupGreaterThan(String value) {
            addCriterion("belong_group >", value, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupGreaterThanOrEqualTo(String value) {
            addCriterion("belong_group >=", value, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupLessThan(String value) {
            addCriterion("belong_group <", value, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupLessThanOrEqualTo(String value) {
            addCriterion("belong_group <=", value, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupLike(String value) {
            addCriterion("belong_group like", value, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupNotLike(String value) {
            addCriterion("belong_group not like", value, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupIn(List<String> values) {
            addCriterion("belong_group in", values, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupNotIn(List<String> values) {
            addCriterion("belong_group not in", values, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupBetween(String value1, String value2) {
            addCriterion("belong_group between", value1, value2, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andBelongGroupNotBetween(String value1, String value2) {
            addCriterion("belong_group not between", value1, value2, "belongGroup");
            return (Criteria) this;
        }

        public Criteria andMainCabIsNull() {
            addCriterion("main_cab is null");
            return (Criteria) this;
        }

        public Criteria andMainCabIsNotNull() {
            addCriterion("main_cab is not null");
            return (Criteria) this;
        }

        public Criteria andMainCabEqualTo(String value) {
            addCriterion("main_cab =", value, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabNotEqualTo(String value) {
            addCriterion("main_cab <>", value, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabGreaterThan(String value) {
            addCriterion("main_cab >", value, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabGreaterThanOrEqualTo(String value) {
            addCriterion("main_cab >=", value, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabLessThan(String value) {
            addCriterion("main_cab <", value, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabLessThanOrEqualTo(String value) {
            addCriterion("main_cab <=", value, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabLike(String value) {
            addCriterion("main_cab like", value, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabNotLike(String value) {
            addCriterion("main_cab not like", value, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabIn(List<String> values) {
            addCriterion("main_cab in", values, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabNotIn(List<String> values) {
            addCriterion("main_cab not in", values, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabBetween(String value1, String value2) {
            addCriterion("main_cab between", value1, value2, "mainCab");
            return (Criteria) this;
        }

        public Criteria andMainCabNotBetween(String value1, String value2) {
            addCriterion("main_cab not between", value1, value2, "mainCab");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("region like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("region not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andCooperationIsNull() {
            addCriterion("cooperation is null");
            return (Criteria) this;
        }

        public Criteria andCooperationIsNotNull() {
            addCriterion("cooperation is not null");
            return (Criteria) this;
        }

        public Criteria andCooperationEqualTo(Short value) {
            addCriterion("cooperation =", value, "cooperation");
            return (Criteria) this;
        }

        public Criteria andCooperationNotEqualTo(Short value) {
            addCriterion("cooperation <>", value, "cooperation");
            return (Criteria) this;
        }

        public Criteria andCooperationGreaterThan(Short value) {
            addCriterion("cooperation >", value, "cooperation");
            return (Criteria) this;
        }

        public Criteria andCooperationGreaterThanOrEqualTo(Short value) {
            addCriterion("cooperation >=", value, "cooperation");
            return (Criteria) this;
        }

        public Criteria andCooperationLessThan(Short value) {
            addCriterion("cooperation <", value, "cooperation");
            return (Criteria) this;
        }

        public Criteria andCooperationLessThanOrEqualTo(Short value) {
            addCriterion("cooperation <=", value, "cooperation");
            return (Criteria) this;
        }

        public Criteria andCooperationIn(List<Short> values) {
            addCriterion("cooperation in", values, "cooperation");
            return (Criteria) this;
        }

        public Criteria andCooperationNotIn(List<Short> values) {
            addCriterion("cooperation not in", values, "cooperation");
            return (Criteria) this;
        }

        public Criteria andCooperationBetween(Short value1, Short value2) {
            addCriterion("cooperation between", value1, value2, "cooperation");
            return (Criteria) this;
        }

        public Criteria andCooperationNotBetween(Short value1, Short value2) {
            addCriterion("cooperation not between", value1, value2, "cooperation");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeIsNull() {
            addCriterion("cooperation_time is null");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeIsNotNull() {
            addCriterion("cooperation_time is not null");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeEqualTo(Date value) {
            addCriterion("cooperation_time =", value, "cooperationTime");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeNotEqualTo(Date value) {
            addCriterion("cooperation_time <>", value, "cooperationTime");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeGreaterThan(Date value) {
            addCriterion("cooperation_time >", value, "cooperationTime");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cooperation_time >=", value, "cooperationTime");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeLessThan(Date value) {
            addCriterion("cooperation_time <", value, "cooperationTime");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeLessThanOrEqualTo(Date value) {
            addCriterion("cooperation_time <=", value, "cooperationTime");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeIn(List<Date> values) {
            addCriterion("cooperation_time in", values, "cooperationTime");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeNotIn(List<Date> values) {
            addCriterion("cooperation_time not in", values, "cooperationTime");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeBetween(Date value1, Date value2) {
            addCriterion("cooperation_time between", value1, value2, "cooperationTime");
            return (Criteria) this;
        }

        public Criteria andCooperationTimeNotBetween(Date value1, Date value2) {
            addCriterion("cooperation_time not between", value1, value2, "cooperationTime");
            return (Criteria) this;
        }

        public Criteria andPremiumIsNull() {
            addCriterion("premium is null");
            return (Criteria) this;
        }

        public Criteria andPremiumIsNotNull() {
            addCriterion("premium is not null");
            return (Criteria) this;
        }

        public Criteria andPremiumEqualTo(BigDecimal value) {
            addCriterion("premium =", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotEqualTo(BigDecimal value) {
            addCriterion("premium <>", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumGreaterThan(BigDecimal value) {
            addCriterion("premium >", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("premium >=", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumLessThan(BigDecimal value) {
            addCriterion("premium <", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("premium <=", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumIn(List<BigDecimal> values) {
            addCriterion("premium in", values, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotIn(List<BigDecimal> values) {
            addCriterion("premium not in", values, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("premium between", value1, value2, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("premium not between", value1, value2, "premium");
            return (Criteria) this;
        }

        public Criteria andReplaceRateIsNull() {
            addCriterion("replace_rate is null");
            return (Criteria) this;
        }

        public Criteria andReplaceRateIsNotNull() {
            addCriterion("replace_rate is not null");
            return (Criteria) this;
        }

        public Criteria andReplaceRateEqualTo(BigDecimal value) {
            addCriterion("replace_rate =", value, "replaceRate");
            return (Criteria) this;
        }

        public Criteria andReplaceRateNotEqualTo(BigDecimal value) {
            addCriterion("replace_rate <>", value, "replaceRate");
            return (Criteria) this;
        }

        public Criteria andReplaceRateGreaterThan(BigDecimal value) {
            addCriterion("replace_rate >", value, "replaceRate");
            return (Criteria) this;
        }

        public Criteria andReplaceRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("replace_rate >=", value, "replaceRate");
            return (Criteria) this;
        }

        public Criteria andReplaceRateLessThan(BigDecimal value) {
            addCriterion("replace_rate <", value, "replaceRate");
            return (Criteria) this;
        }

        public Criteria andReplaceRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("replace_rate <=", value, "replaceRate");
            return (Criteria) this;
        }

        public Criteria andReplaceRateIn(List<BigDecimal> values) {
            addCriterion("replace_rate in", values, "replaceRate");
            return (Criteria) this;
        }

        public Criteria andReplaceRateNotIn(List<BigDecimal> values) {
            addCriterion("replace_rate not in", values, "replaceRate");
            return (Criteria) this;
        }

        public Criteria andReplaceRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("replace_rate between", value1, value2, "replaceRate");
            return (Criteria) this;
        }

        public Criteria andReplaceRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("replace_rate not between", value1, value2, "replaceRate");
            return (Criteria) this;
        }

        public Criteria andLossRationIsNull() {
            addCriterion("loss_ration is null");
            return (Criteria) this;
        }

        public Criteria andLossRationIsNotNull() {
            addCriterion("loss_ration is not null");
            return (Criteria) this;
        }

        public Criteria andLossRationEqualTo(BigDecimal value) {
            addCriterion("loss_ration =", value, "lossRation");
            return (Criteria) this;
        }

        public Criteria andLossRationNotEqualTo(BigDecimal value) {
            addCriterion("loss_ration <>", value, "lossRation");
            return (Criteria) this;
        }

        public Criteria andLossRationGreaterThan(BigDecimal value) {
            addCriterion("loss_ration >", value, "lossRation");
            return (Criteria) this;
        }

        public Criteria andLossRationGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("loss_ration >=", value, "lossRation");
            return (Criteria) this;
        }

        public Criteria andLossRationLessThan(BigDecimal value) {
            addCriterion("loss_ration <", value, "lossRation");
            return (Criteria) this;
        }

        public Criteria andLossRationLessThanOrEqualTo(BigDecimal value) {
            addCriterion("loss_ration <=", value, "lossRation");
            return (Criteria) this;
        }

        public Criteria andLossRationIn(List<BigDecimal> values) {
            addCriterion("loss_ration in", values, "lossRation");
            return (Criteria) this;
        }

        public Criteria andLossRationNotIn(List<BigDecimal> values) {
            addCriterion("loss_ration not in", values, "lossRation");
            return (Criteria) this;
        }

        public Criteria andLossRationBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("loss_ration between", value1, value2, "lossRation");
            return (Criteria) this;
        }

        public Criteria andLossRationNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("loss_ration not between", value1, value2, "lossRation");
            return (Criteria) this;
        }

        public Criteria andCenterPositionIsNull() {
            addCriterion("center_position is null");
            return (Criteria) this;
        }

        public Criteria andCenterPositionIsNotNull() {
            addCriterion("center_position is not null");
            return (Criteria) this;
        }

        public Criteria andCenterPositionEqualTo(String value) {
            addCriterion("center_position =", value, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionNotEqualTo(String value) {
            addCriterion("center_position <>", value, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionGreaterThan(String value) {
            addCriterion("center_position >", value, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionGreaterThanOrEqualTo(String value) {
            addCriterion("center_position >=", value, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionLessThan(String value) {
            addCriterion("center_position <", value, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionLessThanOrEqualTo(String value) {
            addCriterion("center_position <=", value, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionLike(String value) {
            addCriterion("center_position like", value, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionNotLike(String value) {
            addCriterion("center_position not like", value, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionIn(List<String> values) {
            addCriterion("center_position in", values, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionNotIn(List<String> values) {
            addCriterion("center_position not in", values, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionBetween(String value1, String value2) {
            addCriterion("center_position between", value1, value2, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andCenterPositionNotBetween(String value1, String value2) {
            addCriterion("center_position not between", value1, value2, "centerPosition");
            return (Criteria) this;
        }

        public Criteria andZhigongsiIsNull() {
            addCriterion("zhigongsi is null");
            return (Criteria) this;
        }

        public Criteria andZhigongsiIsNotNull() {
            addCriterion("zhigongsi is not null");
            return (Criteria) this;
        }

        public Criteria andZhigongsiEqualTo(String value) {
            addCriterion("zhigongsi =", value, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiNotEqualTo(String value) {
            addCriterion("zhigongsi <>", value, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiGreaterThan(String value) {
            addCriterion("zhigongsi >", value, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiGreaterThanOrEqualTo(String value) {
            addCriterion("zhigongsi >=", value, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiLessThan(String value) {
            addCriterion("zhigongsi <", value, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiLessThanOrEqualTo(String value) {
            addCriterion("zhigongsi <=", value, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiLike(String value) {
            addCriterion("zhigongsi like", value, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiNotLike(String value) {
            addCriterion("zhigongsi not like", value, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiIn(List<String> values) {
            addCriterion("zhigongsi in", values, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiNotIn(List<String> values) {
            addCriterion("zhigongsi not in", values, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiBetween(String value1, String value2) {
            addCriterion("zhigongsi between", value1, value2, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andZhigongsiNotBetween(String value1, String value2) {
            addCriterion("zhigongsi not between", value1, value2, "zhigongsi");
            return (Criteria) this;
        }

        public Criteria andYewuyuanIsNull() {
            addCriterion("yewuyuan is null");
            return (Criteria) this;
        }

        public Criteria andYewuyuanIsNotNull() {
            addCriterion("yewuyuan is not null");
            return (Criteria) this;
        }

        public Criteria andYewuyuanEqualTo(String value) {
            addCriterion("yewuyuan =", value, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanNotEqualTo(String value) {
            addCriterion("yewuyuan <>", value, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanGreaterThan(String value) {
            addCriterion("yewuyuan >", value, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanGreaterThanOrEqualTo(String value) {
            addCriterion("yewuyuan >=", value, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanLessThan(String value) {
            addCriterion("yewuyuan <", value, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanLessThanOrEqualTo(String value) {
            addCriterion("yewuyuan <=", value, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanLike(String value) {
            addCriterion("yewuyuan like", value, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanNotLike(String value) {
            addCriterion("yewuyuan not like", value, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanIn(List<String> values) {
            addCriterion("yewuyuan in", values, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanNotIn(List<String> values) {
            addCriterion("yewuyuan not in", values, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanBetween(String value1, String value2) {
            addCriterion("yewuyuan between", value1, value2, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andYewuyuanNotBetween(String value1, String value2) {
            addCriterion("yewuyuan not between", value1, value2, "yewuyuan");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey_center
     *
     * @mbggenerated do_not_delete_during_merge Fri May 11 09:28:30 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey_center
     *
     * @mbggenerated Fri May 11 09:28:30 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}