package com.emate.shop.mapper;

import com.emate.shop.business.model.AutoInfo;
import com.emate.shop.business.model.AutoInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    int countByExample(AutoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    int deleteByExample(AutoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    int insert(AutoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    int insertSelective(AutoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    List<AutoInfo> selectByExample(AutoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    AutoInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") AutoInfo record, @Param("example") AutoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    int updateByExample(@Param("record") AutoInfo record, @Param("example") AutoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    int updateByPrimaryKeySelective(AutoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_info
     *
     * @mbggenerated Thu Dec 29 13:28:33 CST 2016
     */
    int updateByPrimaryKey(AutoInfo record);
}