package com.emate.shop.mapper;

import com.emate.shop.business.model.SellerReport;
import com.emate.shop.business.model.SellerReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SellerReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    int countByExample(SellerReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    int deleteByExample(SellerReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    int insert(SellerReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    int insertSelective(SellerReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    List<SellerReport> selectByExample(SellerReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    SellerReport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") SellerReport record, @Param("example") SellerReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    int updateByExample(@Param("record") SellerReport record, @Param("example") SellerReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    int updateByPrimaryKeySelective(SellerReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_report
     *
     * @mbggenerated Tue Feb 21 10:20:49 CST 2017
     */
    int updateByPrimaryKey(SellerReport record);
}